pred_dim: 4
batch_size: 64
num_epochs: 100
# loss: cosine
loss: shapematch
n_blocks: 0 # blk is split_resnet, or using surface pc
reg: 7
max_angle: 30
image_dim: 128
split_resnet: 0
load_orienting_model: 0