pred_dim: 4
batch_size: 64
num_epochs: 50
n_blocks: 1
embed_dim: 1024
# loss: cosine
loss: shapematch
losses_f_name: results/546objv4_cos_sm.p
loss_plot_f_name: plots/546objv4_cos_sm_loss.png
rotation_predictions_plot: plots/546objv4_cos_sm_rot.png
final_epoch_dir: models/546objv4_cos_sm.pt
best_epoch_dir: models/546objv4_cos_sm_best.pt
test_epoch_dir: models/546objv4_cos_sm_best.pt
hist_data: results/546objv4_cos_sm_histdata.txt

# losses_f_name: results/best_scoresv5_cos_sm.p
# loss_plot_f_name: plots/best_scoresv5_cos_sm_loss.png
# rotation_predictions_plot: plots/best_scoresv5_cos_sm_rot.png
# final_epoch_dir: models/best_scoresv5_cos_sm.pt
# best_epoch_dir: models/best_scoresv5_cos_sm_best.pt
# test_epoch_dir: models/best_scoresv5_cos_sm_best.pt
# hist_data: results/best_scoresv5_cos_sm_histdata.txt

# test_epoch_dir: models/564obj_1024.pt
# test_epoch_dir: models/uniform30_1e7.pt
