pred_dim: 4
batch_size: 256
num_epochs: 100
losses_f_name: results/losses_free_space_axis_pred.p
losses_plot_f_name: plots/losses_free_space_axis_pred.png
accs_plot_f_name: plots/accs_free_space_axis_pred.png
unsup_model_save_dir: /nfs/diskstation/projects/unsupervised_rbt/models/ResNet_xyz-axis1_block_20_embed.pkl
model_save_dir: models/embedding_obj_prediction.pt
